bc-cbuilder
Compiler-CampusMinden/CB-Vorlesung pull request #124
Opened 2022-12-09 18:00 UTC by bcg7

2022-12-10 08:23 UTC, cagix commented
die annotierten slides fehlen noch im anderen repo, oder?

2022-12-10 16:59 UTC, cagix requested changes
Ein paar Vorschläge ...

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +    -   topic: Meilenstein 04
```suggestion
    -   topic: sheet04
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +## Methoden: *__init__(self)* anlegen
```suggestion
## Methoden: *\_\_init\_\_(self)* anlegen
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +Methoden werden vom CBuilder in normale Funktionen umgesetzt, d. h. gleichnamige Methoden in unterschidleichen Klassen würden zu Fehlern führen. Eindeutige Namen werden automatisch durch die Funktion
```suggestion
Methoden werden vom CBuilder in normale Funktionen umgesetzt, d. h. gleichnamige Methoden in unterschidleichen Klassen würden zu Fehlern führen. Eindeutige Namen werden automatisch durch die Methode `Function#createUniqueCName()` im Konstruktor erzeugt.
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   in \_\_init\_\_ **muss** als erstes *super* (Klasse *SuperCall* aufgerufen werden
```suggestion
*   in `__init__()` **muss** als erstes `super` (Klasse `SuperCall` aufgerufen werden
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   \_\_init\_\_ muss **immer** implementiert werden
```suggestion
*   `__init__()` muss **immer** implementiert werden
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   \_\_init\_\_ muss **immer** implementiert werden
```suggestion
*   `__init__()` muss **immer** implementiert werden
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   Angabe der Referenz auf Elternklasse (\_\_MPytype_Object, wenn keine eigene Oberklasse vorhanden ist)
```suggestion
*   Angabe der Referenz auf Elternklasse (`__MPytype_Object`, wenn keine eigene Oberklasse vorhanden ist)
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   das Antler-Projekt hineinkopieren
```suggestion
*   das ANTLR-Projekt hineinkopieren
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   das Repo clonen: ergibt CBuilder-Gradle-Projekt (build.gradle im Hauptverzeichnis vom Gitrepo)
```suggestion
*   das Repo clonen: ergibt CBuilder-Gradle-Projekt (`build.gradle` im Hauptverzeichnis vom Gitrepo)
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   wenn der Zielprozesser nicht sehr mächtig ist
```suggestion
*   wenn der Zielprozessor nicht sehr mächtig ist
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   maschinenunabhängige Analysen und Optimierungen (z. B. dead code elimination)
```suggestion
*   maschinenunabhängige Analysen und Optimierungen (z. B. _dead code elimination_)
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   verschiedene Frontends (Sprachen) können denselben Zwischencode (Bakcend) benutzen
```suggestion
*   verschiedene Frontends (Sprachen) können denselben Zwischencode (Backend) benutzen
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +https://github.com/Compiler-CampusMinden/Mini-Python-Builder
```suggestion
[https://github.com/Compiler-CampusMinden/Mini-Python-Builder](https://github.com/Compiler-CampusMinden/Mini-Python-Builder)
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +1)  mit **MSYS2** arbeiten (**pacman -S make** und **pacman -S gcc** aufrufen)  oder
```suggestion
1)  mit **MSYS2** arbeiten (**`pacman -S make`** und **`pacman -S gcc`** zur Installation von Make und GCC aufrufen)  oder
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   den CBuilder ausführen (z. B. über gradle.run). Das generierte C-Programm wird z. B. in das Verzeichnis **./src/program.c** geschrieben.
```suggestion
*   den CBuilder ausführen (z. B. über `./gradlew run`). Das generierte C-Programm wird z. B. in das Verzeichnis **`./src/program.c`** geschrieben.
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   in diesem Verzeichnis **make** aufrufen: **make all** übersetzt das Programm, **make run** führt es auch aus, **make clean** entfernt überflüssige erzeugte Dateien..
```suggestion
*   in diesem Verzeichnis **Make** aufrufen: **`make all`** übersetzt das Programm, **`make run`** führt es auch aus, **`make clean`** entfernt überflüssige erzeugte Dateien.
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   Das übersetzte Programm (in *./bin/program*) läuft in einer Konsole (mit *input*- und *print*-Anweisungen)
```suggestion
*   Das übersetzte Programm (*`./bin/program`*) läuft in einer Konsole (mit *`input`*- und *`print`*-Anweisungen)
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +Arithmetische Operatoren werden in Form von Methodenaufrufen realisiert. Das geht, weil alle Variablen in Python von *object* erben, wo die Operatoren als Methoden definiert sind (und man sie so auch
```suggestion
Arithmetische Operatoren werden in Form von Methodenaufrufen realisiert. Das geht, weil alle Variablen in Python von `object` erben, wo die Operatoren als Methoden definiert sind (und man sie so auch überladen kann).
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   Typ **MPyClass**
```suggestion
*   Typ **`MPyClass`**
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   C-compiler existiert für fast alle Plattformen
```suggestion
*   C-Compiler existiert für fast alle Plattformen
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   Mainklasse festlegen (siehe Doku)
```suggestion
*   Main-Klasse festlegen (siehe Doku)
```

2022-12-10 16:59 UTC, cagix commented on markdown/backend/minipython-builder.ba.md
> +*   Alle Methodendefinitinen **müssen** als ersten Parameter **self** enthalten, nicht jedoch die Methodenaufrufe.
```suggestion
*   Alle Methodendefinitinen **müssen** als ersten Parameter **`self`** enthalten, nicht jedoch die Methodenaufrufe.
```

2022-12-10 17:21 UTC, bcg7 commented
@cagix Das hättest du ruhig an mich "zurücküberweisen" können. Was muss ich jetzt tun? Jedes Kästchen "resolven"?

2022-12-10 18:41 UTC, cagix commented
ja, wenn du den vorschlägen zustimmst :)

2022-12-10 20:35 UTC, bcg7 commented
@cagix Ich schließe den Pull Request.

2022-12-10 20:37 UTC, bcg7 commented
@cagix Es hab noch ein paar hidden conversations, die ich jetzt nachträglich geschlossen habe. Muss ich den Branch jetzt neu öffnen?

2022-12-10 21:24 UTC, cagix commented
> @cagix Ich schließe den Pull Request.

warum denn? wir haben doch gar bicht gemerged?

2022-12-10 21:25 UTC, cagix commented
ich schaue morgen vom rechner nochmal drauf, in der blöden app ist das zu unübersichtlich...

2022-12-10 21:27 UTC, bcg7 commented
@cagix Ich dachte, Schließen meint vielleicht: Fertig zum Mergen.

2022-12-11 10:36 UTC, cagix commented
> @cagix Ich dachte, Schließen meint vielleicht: Fertig zum Mergen.

@bcg7 neee, schließen ist "abandoned" ...

2022-12-11 12:11 UTC, bcg7 commented
@cagix  Github schreibt: 1 review requesting changes by reviewers with write access. 
Aber ich finde keinen Review, der zu tun ist.

2022-12-11 13:35 UTC, cagix commented
> @cagix Github schreibt: 1 review requesting changes by reviewers with write access.
> Aber ich finde keinen Review, der zu tun ist.

@bcg7 Das Repo ist so eingestellt, dass Merges in den Master ein Review brauchen, welches aber nicht vom Einreicher kommt. Deshalb steht ganz unten "Merging is blocked", weil es noch kein solches Review gab. Außerdem gibt es noch "Changes requested", das waren die Vorschläge, die ich gestern am Handy eingetippert hatte.

Man kann ein Review ausrufen: Oben rechts eine Person zum Reviewer ernennen. Da kann man sich aber als Ersteller eines PR nicht selbst auswählen :)

Und oben über "Files changed" kann man auch sonst ein Review machen (again, das geht nicht für jemanden, der den PR erstellt hat).

---

Ich gehe jetzt nochmal über die Änderungsvorschläge und teste das generierte Web-Skript, und dann geb ich frei+merge+lade das Ergebnis ins ILIAS hoch :)

2022-12-11 13:48 UTC, cagix commented
@bcg7 Wenn Du bei den Vorschlägen auf "Resolve" klickst, wird die "Diskussion" nur geschlossen, aber die Vorschläge nicht übernommen. Bei "Commit" werden die Vorschläge übernommen und die Diskussion damit resolved ...

2022-12-11 14:52 UTC, cagix approved these changes
@bcg7 Ich glaube, so könnte es jetzt gehen :)  Sieht lokal sowohl im PDF als auch HTML sinnvoll aus.

2022-12-11 14:56 UTC, merged

2022-12-11 15:18 UTC, cagix commented
@bcg7 Ist im ILIAS :)