[SHEETS] edited task sheets
Compiler-CampusMinden/CB-Vorlesung pull request #79
Opened 2022-10-02 15:48 UTC by mpeters4

#62

2022-10-02 16:17 UTC, cagix requested changes
D.h. eigentlich sollen die Studis `input()` und `write()` als native Funktionen implementieren, richtig? Kannst Du das noch so umbauen bitte?

2022-10-02 16:41 UTC, mpeters4 commented
> D.h. eigentlich sollen die Studis `input()` und `write()` als native Funktionen implementieren, richtig? Kannst Du das noch so umbauen bitte?

Erledigt!

2022-10-02 16:58 UTC, mpeters4 commented
@cagix 
Blatt01:
- Bitte einmal über Blatt01ba schauen. Wenn die Änderungen passen, kopiere ich diese in das Blatt01ma
- Bitte einmal über den Sprachumfang schauen. Dieses muss nach dem erstellen in das Wiki aufgenommen werden. 

Die weiteren Blätter sollten wir kurz im Meeting am 05.10.22 besprechen.

2022-10-02 17:19 UTC, cagix reviewed
Könnte so gehen. Der Link ins Wiki muss natürlich noch angepasst werden, aber dazu müsste @CrappyAlgorithm bitte noch die Doku-Seite finalisieren und das Studi-Repo mit Builder und Wiki müsste @cagix noch anlegen. Ist der Builder schon reif für den Split?

Ich hatte noch überlegt, ob man Stichpunkte ala "Beispiel für `if`" anlegt und die Codeblöcke darunter schiebt (mit entsprechender Einrückung). Dann hat es mehr Struktur und die Kommentare könnten aus den Snippets raus.

2022-10-02 17:19 UTC, cagix commented on markdown/assignments/sheet03.ba.md
>  <!-- TODO Abstimmung mit Florian/Sebastian/Michael -->
das kann dann noch raus :)

2022-10-02 17:19 UTC, cagix commented on markdown/assignments/sheet01.ba.md
>  Sie den minimalen Funktionsumfang ablesen.
Der zweite Satz hier ("An folgenden...ablesen.") kann jetzt weg, oder?

2022-10-02 17:19 UTC, cagix commented on markdown/assignments/sheet01.ba.md
> +
```suggestion

Beispiele:
```

2022-10-03 07:06 UTC, mpeters4 commented on markdown/assignments/sheet03.ba.md
>  <!-- TODO Abstimmung mit Florian/Sebastian/Michael -->
Erledigt!

2022-10-03 07:06 UTC, mpeters4 commented on markdown/assignments/sheet01.ba.md
>  Sie den minimalen Funktionsumfang ablesen.
Erledigt!

2022-10-03 07:08 UTC, mpeters4 commented on markdown/assignments/sheet01.ba.md
> +
Codebeispiele haben jetzt Überschriften. Sieht besser aus.

2022-10-04 11:27 UTC, CrappyAlgorithm commented
> Könnte so gehen. Der Link ins Wiki muss natürlich noch angepasst werden, aber dazu müsste @CrappyAlgorithm bitte noch die Doku-Seite finalisieren und das Studi-Repo mit Builder und Wiki müsste @cagix noch anlegen. Ist der Builder schon reif für den Split?

Wie in #80 geschrieben sollte die Doku zum Sprachumfang fertig sein. Der Builder ist aber noch nicht ganz fertig und soll  dann auch noch eine weitere Doku zur Verwendung bekommen.

2022-10-04 16:26 UTC, cagix commented
> > Könnte so gehen. Der Link ins Wiki muss natürlich noch angepasst werden, aber dazu müsste @CrappyAlgorithm bitte noch die Doku-Seite finalisieren und das Studi-Repo mit Builder und Wiki müsste @cagix noch anlegen. Ist der Builder schon reif für den Split?
> 
> Wie in #80 geschrieben sollte die Doku zum Sprachumfang fertig sein. Der Builder ist aber noch nicht ganz fertig und soll dann auch noch eine weitere Doku zur Verwendung bekommen.

@CrappyAlgorithm Ich habe das neue [Repo](https://github.com/Compiler-CampusMinden/Mini-Python-Builder) für die Studis aufgemacht, dort solltest Du eine Wiki-Seite anlegen können. Wie besprochen - der aktualisierte Inhalt von http://github.com/Compiler-CampusMinden/Mini-Python/blob/main/doc/supported_features.md, nur ohne die letzten beiden Spalten.

2022-10-13 15:47 UTC, CrappyAlgorithm requested changes
Jetzt sind es wirklich nur noch Kleinigkeiten.

2022-10-13 15:47 UTC, CrappyAlgorithm commented on markdown/assignments/sheet01.ba.md
> +* [Sprachumfang](https://github.com/Compiler-CampusMinden/Mini-Python)
```suggestion
* [Sprachumfang](https://github.com/Compiler-CampusMinden/Mini-Python-Builder/wiki/Definition-der-syntaktischen-Sprachelemente)
```

2022-10-13 15:47 UTC, CrappyAlgorithm commented on markdown/assignments/sheet01.ma.md
> +* [Sprachumfang](https://github.com/Compiler-CampusMinden/Mini-Python)
```suggestion
* [Sprachumfang](https://github.com/Compiler-CampusMinden/Mini-Python-Builder/wiki/Definition-der-syntaktischen-Sprachelemente)
```

2022-10-13 15:47 UTC, CrappyAlgorithm commented on markdown/assignments/sheet01.ba.md
> +Beispiele für IF-Statements:
Die Beispiel könnten auf dem Blatt auch entfernt werden.

2022-10-13 15:47 UTC, CrappyAlgorithm commented on markdown/assignments/sheet01.ma.md
> +Beispiele für IF-Statements:
Das mit den Beispielen gilt natürlich auch für das Blatt im Master.

2022-10-16 13:02 UTC, cagix commented
Ich würde gern B01 rausgeben, aber in diesem PR ist auch noch B03 drin. Deshalb habe ich die Commit mit cherry-pick übernommen und #89 und #90 aufgemacht. Hier wird geschlossen.

2022-10-16 13:02 UTC, closed without merging